#!/usr/bin/env bash
# Install HAProxy

sudo apt update
sudo apt install -y haproxy

# Append configuration to HAProxy config file using sed
sudo sed -i '$ a\
frontend http-in\n\
    bind *:80\n\
    default_backend web-servers\n\
\n\
backend web-servers\n\
    balance roundrobin\n\
    server 129219-web-01 100.25.2.85:80 check\n\
    server 129219-web-02 18.204.5.189:80 check\n\
' /etc/haproxy/haproxy.cfg

# Restart HAProxy and enable it on boot
sudo /etc/init.d/haproxy start

# set HAProxy to start at boot
sudo update-rc.d haproxy defaults

# reload HAProxy configuration
sudo /etc/init.d/haproxy reload
